apiVersion: v1
kind: ServiceAccount
metadata:
  name: btf-pid-eks-admin-prd-sa-01
  namespace: default  
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: btf-pid-eks-admin-prd-srt-01
  annotations:
    kubernetes.io/service-account.name: btf-pid-eks-admin-prd-sa-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: btf-pid-eks-admin-prd-crb-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: btf-pid-eks-admin-prd-sa-01
  namespace: default  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: btf-pid-eks-ro-prd-sa-01
  namespace: default

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: btf-pid-eks-ro-prd-srt-01
  annotations:
    kubernetes.io/service-account.name: btf-pid-eks-ro-prd-sa-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-log-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  - replicationcontrollers
  - pods/log
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: btf-pid-eks-ro-prd-crb-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-only-log-role
subjects:
- kind: ServiceAccount
  name: btf-pid-eks-ro-prd-sa-01
  namespace: default